### PR TITLE
Throw if the library is used before being initialized (BL-13266)

### PR DESCRIPTION
**Pull request by andrew-polk**
+semver: major

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/120)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Looks good with a couple of questions that don't necessarily require any code changes.  Possibly a comment in the test code, but maybe not even that.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-:-Nvcxs-X5Aq6YGdjx4gn:bmcq0g)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-Nvcx3cOEhPs7Cwm9kGH:-Nvcx3cOEhPs7Cwm9kGI:boh5ry4) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c86c502fa24480545476e69c4d81cc07965c94c5/src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs#L33)):*
> ```Smalltalk
> 				LocalizationManager.UILanguageId = "en";
> 				Assert.That(
> 					LocalizationManager.GetDynamicString("Glom", "prefix.data", "data"),
> ```

So I assume that GetDynamicString (and GetDynamicStringOrEnglish) do not use the code paths that trap and report the error?  Is that because they both provide the name/id of the specific LocalizationManager needed, and presumably loaded since the programmer knows about it?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/120)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-Nvcx3cOEhPs7Cwm9kGH:-NvdETP1CLvkS3ZyDZNk:bhdgx4r) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c86c502fa24480545476e69c4d81cc07965c94c5/src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs#L33)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

So I assume that GetDynamicString (and GetDynamicStringOrEnglish) do not use the code paths that trap and report the error?  Is that because they both provide the name/id of the specific LocalizationManager needed, and presumably loaded since the programmer knows about it?
</blockquote></details>

Actually, it's because that code path has the following:
```
			//this happens in unit test environments or apps that
			//have imported a library that is L10N'ized, but the app
			//itself isn't initializing L10N yet.
			if (LoadedManagers.Count == 0)
			{
				if (PreviouslyLoadedManagers.Contains(appId))
				{
					if (LocalizationManager.ThrowIfManagerDisposed)
					{
						throw new ObjectDisposedException(
							$"The application id '{appId}' refers to a LocalizationManagerInternal that has been disposed");
					}
					return string.IsNullOrEmpty(englishText) ? id : englishText;
				}

				if (!string.IsNullOrEmpty(englishText) && langId == LocalizationManager.kDefaultLang)
					return englishText;
				return id;
			}
```
which I didn't want to attempt to mess with.

The good thing is that code path doesn't set the mapping, so it doesn't actually break anything.

I'm definitely open to suggestions on how to improve commenting around this.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/120)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs` line 94 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-NvgsNom3L_h4r0Qy_iN:-NvgsNon8XzTR1PgLxZJ:b-sto2lx) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c86c502fa24480545476e69c4d81cc07965c94c5/src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs#L94)):*
> ```Smalltalk
> 
> 				Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo(cultureName);
> 				//LocalizationManager.UILanguageId = cultureName;
> ```

Was this commented line left in for a reason?

**Comment by andrew-polk** [comment]
*[`src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs` line 94 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-NvgsNom3L_h4r0Qy_iN:-Nvh4J3P2O20ReBJWsIF:bcf5hlg) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c86c502fa24480545476e69c4d81cc07965c94c5/src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs#L94)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Was this commented line left in for a reason?
</blockquote></details>

Nope! Fixed.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/120)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Comment by tombogle** [comment]
*[`src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/120#-Nvcx3cOEhPs7Cwm9kGH:-Nvlg_5O3tAwORPtpabF:b-9k47p6) ([raw file](https://github.com/sillsdev/l10nsharp/blob/c86c502fa24480545476e69c4d81cc07965c94c5/src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, it's because that code path has the following:
```
			//this happens in unit test environments or apps that
			//have imported a library that is L10N'ized, but the app
			//itself isn't initializing L10N yet.
			if (LoadedManagers.Count == 0)
			{
				if (PreviouslyLoadedManagers.Contains(appId))
				{
					if (LocalizationManager.ThrowIfManagerDisposed)
					{
						throw new ObjectDisposedException(
							$"The application id '{appId}' refers to a LocalizationManagerInternal that has been disposed");
					}
					return string.IsNullOrEmpty(englishText) ? id : englishText;
				}

				if (!string.IsNullOrEmpty(englishText) && langId == LocalizationManager.kDefaultLang)
					return englishText;
				return id;
			}
```
which I didn't want to attempt to mess with.

The good thing is that code path doesn't set the mapping, so it doesn't actually break anything.

I'm definitely open to suggestions on how to improve commenting around this.
</blockquote></details>

It would probably be safe to check that flagg and throw that same InvalidOperationException if there are 0 loaded managers and 0 previously loaded managers. But it's probably okay to just leave it as is.

**Pull request merged**
