### PR TITLE
Added line back in which breaks display of strings in localization dialog

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/7)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/7#-:-KUXzMHZJHVPl3zeH1Y_:bnfp4nl)*

**Comment by jasonleenaylor** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/sillsdev/l10nsharp/7#-KUY0g2Qa3i4C8BI7pqe:-KUY0g2Qa3i4C8BI7pqf:bngzquc) (no related file):*
A unit test would be nice. So we don't break this again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/7)*

**Comment by tombogle** [comment]
*[a discussion](https://reviewable.io:443/reviews/sillsdev/l10nsharp/7#-KUY0g2Qa3i4C8BI7pqe:-KUY6UBoIxdiJb8j1G2E:bhdnda6) (no related file):*
> Reply...
I'll give it a whirl this afternoon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/7)*

**Comment by tombogle** [comment]
I don't know how to use Reviewable, so I can't make it happy. Should I just merge this?

**Pull request merged**
