### PR TITLE
Add CheckOrFixXliff program (BL-5409, BL-5415)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/37)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:
I'm not merging in case our discussion today means more changes. But if that isn't the case, go ahead and merge.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-:-L2VlHbuwfPoiOIfJ5Nf:b-gf1dux)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 457 at r2](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-L2WdmTKmNvY0NaBzPX8:-L2WdmTKmNvY0NaBzPX9:b275rl9) ([raw file](https://github.com/sillsdev/l10nsharp/blob/fd560c951f6645e7e43440e58b56210b630ab0f6/src/L10NSharp/LocalizedStringCache.cs#L457)):*
> ```Smalltalk
> 				value = value.Replace(_ampersandReplacement, "&");
> 
> 			if (langId != "en")
> ```

Seems like we should test at least this new code.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 471 at r2](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-L2WeRVdqCUJsgwrTCyC:-L2WeRVdqCUJsgwrTCyD:b-3yumas) ([raw file](https://github.com/sillsdev/l10nsharp/blob/fd560c951f6645e7e43440e58b56210b630ab0f6/src/L10NSharp/LocalizedStringCache.cs#L471)):*
> ```Smalltalk
> 							return fixedValue;
> 						}
> 						return null;	// don't use an invalid formatting string!
> ```

Wouldn't it be better to return the English?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37)*

**Comment by StephenMcConnel** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 457 at r2](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-L2WdmTKmNvY0NaBzPX8:-L2Wke21RbiBOVmPVVUI:b-un0olc) ([raw file](https://github.com/sillsdev/l10nsharp/blob/fd560c951f6645e7e43440e58b56210b630ab0f6/src/L10NSharp/LocalizedStringCache.cs#L457)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we should test at least this new code.
</blockquote></details>

somehow I knew someone was going to say this...  Done.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 471 at r2](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-L2WeRVdqCUJsgwrTCyC:-L2WkO0rkNGt-gVKKwa5:b753sph) ([raw file](https://github.com/sillsdev/l10nsharp/blob/fd560c951f6645e7e43440e58b56210b630ab0f6/src/L10NSharp/LocalizedStringCache.cs#L471)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Wouldn't it be better to return the English?
</blockquote></details>

no, because places it's called do this already if they want English (or some other language) as a fallback

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/37#-:-L2_NJFOtnLAVeM13J-B:bnfp4nl)*

**Pull request merged**
