### PR TITLE
Add instructions for building with GitVersion

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/88)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Review by tombogle — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Review by tombogle — APPROVED** [review]

**Comment by tombogle** [comment]
@papeh Assuming this is still correct, is there a reason that it is sitting here as a draft and has not been merged?

**Comment by papeh** [comment]
@tombogle, not sure. Perhaps because the CI builds didn't trigger, or perhaps because I don't look at this repository often.

**Comment by papeh** [comment]
Actually, it looks like these changes are no longer necessary. Thanks for bringing this to my attention.

**Pull request closed without merging**
