### PR TITLE
Load Xliff files lazily (BL-10843)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91)* status: 0 of 9 files reviewed, 1 unresolved discussion

___
*[src/L10NSharp/LocalizationManagerInternal.cs, line 80 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-Mw8tETg0b-CrGlFAEqJ:-Mw8tETg0b-CrGlFAEqK:btktf8k) ([raw file](https://github.com/sillsdev/l10nsharp/blob/8d24b7500660697b0388d25ec64d6247cccd509f/src/L10NSharp/LocalizationManagerInternal.cs#L80)):*
> ```Smalltalk
> 		private static bool IsDesiredUiCultureAvailable(string desiredUiLangId)
> 		{
> 			if (IsLocalizationAvailable(desiredUiLangId))
> ```

It's not immediately obvious that this is equivalent to the old code. GetUILanguages has code that appears to handle the possibility of not being able to create a CultureInfo for one of the available localizations, in which case it doesn't include it. But in fact that code is obsolete, since it's now creating instances of our own L10NCultureInfo class, which never throws the exception it is looking for.

**Comment by JohnThomson** [comment]
Temporarily moving to draft status while I figure out what to do about version number, ReadMe, and changelog

**Comment by JohnThomson** [comment]
Now ready to merge. (Wants to go out as at least 5.1 or maybe even 6.0, though 5.0 never got out of beta and has never been downloaded. I believe that change should be made on https://ci.appveyor.com/project/SIL_Language_Technology/l10nsharp.)

**Review by papeh — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-:-MwCz0uO4l6rw_tyuxuk:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @papeh)

___
*[README.md, line 35 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCnK-Q3b2F9EPXjFA1:-MwCnK-Q3b2F9EPXjFA2:bvlaenu) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/README.md#L35)):*
> ```Markdown
> es-ES/Whatever.xlf) or its first component, the actual language tag (Whatever.es.xlf
> or es/Whatever.xlf).
> ```

This comment says some things twice. Also, if I don't care about lazy loading, it's ambiguous whether it applies to me.
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 562 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCr9fm4-vvGmq8LVmI:-MwCr9fm4-vvGmq8LVmJ:bn7k3bd) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L562)):*
> ```Smalltalk
> 			{
> 				return Path.GetFileName(Path.GetDirectoryName(fileName));
> 			}
> ```

this is much nicer :slightly_smiling_face:
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 1357 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCscnZDW27O49bJgex:-MwCscnZDW27O49bJgey:b-3ix779) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L1357)):*
> ```Smalltalk
> 		public IEnumerable<string> GetAvailableUILanguageTags()
> 		{
> 			return StringCache.AvailableLangKeys.ToList();
> ```

You didn't change this, but what does .ToList() gain us if AvailableLangKeys is already the type we're returning?
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 1360 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCrQ8vEoTW68vvGR5Y:-MwCrQ8vEoTW68vvGR5Z:bx2ag03) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L1360)):*
> ```Smalltalk
> 		}
> 
> 		public bool IsUILanguageAvailable(string langId) => StringCache.TryGetDocument(langId, out XLiffDocument dummy);
> ```

use `_`



_Code quote:_
```Smalltalk
XLiffDocument dummy
```
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs, line 173 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCx2jNE21752xAMGEc:-MwCx2jNE21752xAMGEd:blgop5c) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L173)):*
> ```Smalltalk
> 			}
> 
> 			_unloadedXliffDocuments.Remove(langId);
> ```

shouldn't this be fileId?



_Code quote:_
```Smalltalk
langId
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91)* status: all files reviewed, 4 unresolved discussions (waiting on @papeh)

___
*[README.md, line 35 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCnK-Q3b2F9EPXjFA1:-MwD382D896tPqvz7zic:bge6apn) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/README.md#L35)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

This comment says some things twice. Also, if I don't care about lazy loading, it's ambiguous whether it applies to me.
</blockquote></details>

I rewrote the bit about lazy loading. I'm not seeing what you mean about saying things twice.
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 1357 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCscnZDW27O49bJgex:-MwD3od770lcWQw6tiEG:b-4wc0zm) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L1357)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

You didn't change this, but what does .ToList() gain us if AvailableLangKeys is already the type we're returning?
</blockquote></details>

I don't know what the author had in mind. One possibility is that without this, the caller might modify the dictionary (which the enumeration is typically the Keys of) while iterating, which I think is a no-no.
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 1360 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCrQ8vEoTW68vvGR5Y:-MwD4PIa0RQi9u0UDHc3:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L1360)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

use `_`
</blockquote></details>

Done.
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs, line 173 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCx2jNE21752xAMGEc:-MwD6v1_EXi_0kPqVUUX:b-7lnna1) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs#L173)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

shouldn't this be fileId?
</blockquote></details>

Yep.  Good catch.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @papeh)

___
*[README.md, line 35 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCnK-Q3b2F9EPXjFA1:-MwDR41kC7-E5BUXJaWM:b-9l8a5i) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/README.md#L35)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

That looks better.

> These names must match the target-language declared in the XLF for lazy loading to work properly

says the same thing as the first sentence.
</blockquote></details>

I sort of see what you mean, but it's less redundant now that I rewrote the first sentence. At least, I'm not seeing a good way to make it better.
___
*[src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, line 1360 at r3](https://reviewable.io/reviews/sillsdev/l10nsharp/91#-MwCrQ8vEoTW68vvGR5Y:-MwDRRyZCyoFWK9dAInS:bb6un1j) ([raw file](https://github.com/sillsdev/l10nsharp/blob/b0f255a3c853ae86d98624c5d5b2ab07f144d205/src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs#L1360)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I don't think `var` is needed with `_`
</blockquote></details>

Done

**Review by papeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/91)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
