### PR TITLE
Provide an option to not throw if LM disposed (BL-9904)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/86)

### CODE REVIEW

**Review by ermshiperete — COMMENTED** [review]
Looks good.

Since this adds to the API it would be good if the commit message would have a line `+semver:minor`. This also deserves a line in the `CHANGELOG.md` file in the `Unreleased` section, something like:

```
### Added

- option `LocalizationManager.ThrowIfManagerDisposed` to not throw if LM disposed (BL-9904)
```

**Review by JohnThomson — COMMENTED** [review]
Done. (However, Bloom uses this module via npm. So we will need to get it released to be able to use it. What needs to happen to get this change released?)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/86#-:-M_fUw3Q195JEjp-2Q1K:b18h48j)* status: 0 of 3 files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
@johnthomson We just use the beta which is still built and available via nuget.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/86#-:-M_fhH-D7MdUtmuYuZCq:ben7c1q)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Comment by ermshiperete** [comment]
If you want to create a non-beta release:
- update `CHANGELOG.md` with the new version number
- create and push a git tag with the new version number

**Pull request merged**
