### PR TITLE
More inexact language code matching (BL-5479)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Language codes may come from HTML or other sources, not just from
setting the UI language.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/44)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: with minor and optional suggestions/questions

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/L10NSharp/LocalizationManager.cs, line 1360 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-L5sk6Qhxr12WRfEjVHE:-L5sk6Qhxr12WRfEjVHF:b-y2z99r) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f5dc5146661ac97e48f35c4e1eaca9e659fb34b8/src/L10NSharp/LocalizationManager.cs#L1360)):*
> ```Smalltalk
> 				var realLangId =  MapToExistingLanguageIfPossible(langId);
> 				var bestAnswer = LoadedManagers.Values.Select(lm => lm.StringCache.GetValueForExactLangAndId(realLangId, stringId, true))
> 					.FirstOrDefault(text => text != null);
> ```

Should we use IsNullOrEmpty here to match the line below?

---

*[src/L10NSharpTests/LocalizationManagerTests.cs, line 925 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-L5smGELd85a-TILI3d-:-L5smGELd85a-TILI3d0:brd8dvw) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f5dc5146661ac97e48f35c4e1eaca9e659fb34b8/src/L10NSharpTests/LocalizationManagerTests.cs#L925)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void TestMappingLanguageCodesToAvailable()
> ```

This verifies that if we ask for es and have es-ES we get es-ES.
Is it also intended that if we ask for es-ES and have es we get es?
What if we have es-ES and ask for es-HN?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-:-L5snlb1Dxvnf3fjKzYn:b-bznnx0)*

**Comment by StephenMcConnel** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/L10NSharp/LocalizationManager.cs, line 1360 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-L5sk6Qhxr12WRfEjVHE:-L5tPfTQZH0AIX-UHjYD:b-896fix) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f5dc5146661ac97e48f35c4e1eaca9e659fb34b8/src/L10NSharp/LocalizationManager.cs#L1360)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should we use IsNullOrEmpty here to match the line below?
</blockquote></details>

Done.

---

*[src/L10NSharpTests/LocalizationManagerTests.cs, line 925 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-L5smGELd85a-TILI3d-:-L5tPovs4S_lQl7ChYGF:btcm7so) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f5dc5146661ac97e48f35c4e1eaca9e659fb34b8/src/L10NSharpTests/LocalizationManagerTests.cs#L925)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This verifies that if we ask for es and have es-ES we get es-ES.
Is it also intended that if we ask for es-ES and have es we get es?
What if we have es-ES and ask for es-HN?
</blockquote></details>

The last test asks for es-MX when we have es-ES, which is the same as your question.  I've added comments to each of the specific test cases, and slightly reordered them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44)*

**Comment by StephenMcConnel** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/L10NSharpTests/LocalizationManagerTests.cs, line 925 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-L5smGELd85a-TILI3d-:-L5tVrXHclAYg-wiHDsW:b-cajd23) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f5dc5146661ac97e48f35c4e1eaca9e659fb34b8/src/L10NSharpTests/LocalizationManagerTests.cs#L925)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The last test asks for es-MX when we have es-ES, which is the same as your question.  I've added comments to each of the specific test cases, and slightly reordered them.
</blockquote></details>

I've also expanded the tests a bit and fixed the code in response to a test failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/44#-:-L5uXTUiERJELxTrpv-j:bnfp4nl)*

**Pull request merged**
