### PR TITLE
BL-4887 Add Unit test for Newline handling

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/35)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/L10NSharpTests/LocalizationManagerTests.cs, line 799 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35#-L0ps6jEfM6jcJWAmORc:-L0ps6jFxPL1t1Qw0BU6:b-hyx7rc) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f162901dfc52dc61997cff383f0f15cb575b3817/src/L10NSharpTests/LocalizationManagerTests.cs#L799)):*
> ```Smalltalk
> 				Assert.That(manager.StringCache.GetValueForExactLangAndId("fr", "anotherId", false), Is.EqualTo("Two lines of\\nFrench"));
> 				Assert.That(LocalizationManager.GetString("anotherId", "Two lines of" + Environment.NewLine + "English"), Is.EqualTo("Two lines of" + LocalizedStringCache.kOSRealNewline + "French"));
> ```

Add maybe a third check with "\r\n" explicitly in the string being added dynamically instead of Environment.NewLine?  Of course, I'd like to see how the test performs on Linux.  :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35)*

**Comment by StephenMcConnel** [comment]
suggested added check, but otherwise looks like a good added test.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35#-:-L0psjBgTMQRLurhM6YU:b-h45g0g)*

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/L10NSharpTests/LocalizationManagerTests.cs, line 799 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35#-L0ps6jEfM6jcJWAmORc:-L0q7ZAT_zQhcCGaPF6b:b-kw3e8b) ([raw file](https://github.com/sillsdev/l10nsharp/blob/f162901dfc52dc61997cff383f0f15cb575b3817/src/L10NSharpTests/LocalizationManagerTests.cs#L799)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Add maybe a third check with "\r\n" explicitly in the string being added dynamically instead of Environment.NewLine?  Of course, I'd like to see how the test performs on Linux.  :-)
</blockquote></details>

Done. I've made the change I think is needed to make this work on Linux, so maybe you'll actually get some good out of this PR!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35)*

**Comment by StephenMcConnel** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/35#-:-L0qMuBCtLo9bmlDFHLc:bnfp4nl)*

**Pull request merged**
