### PR TITLE
Removed support for TMX-based l10n files

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/101)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/101)* status: all files reviewed, 2 unresolved discussions (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`src/L10NSharp/LocalizationManagerInternal.cs` line 858 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6jkgzv84jwYr_G0Wr-:-N6jkgzv84jwYr_G0Wr0:brjdvbd) ([raw file](https://github.com/sillsdev/l10nsharp/blob/29d92a24a5dd092c5840ef04276a95017efe03f7/src/L10NSharp/LocalizationManagerInternal.cs#L858)):*
> ```Smalltalk
> 				return;
> 			var oldDocPath = Path.Combine(installedStringFileFolder,
> 				LocalizationManager.GetTranslationFileNameForLanguage(appId, "en", "tmx"));
> ```

Why does this always want to be "tmx"?
___
*[`src/SampleApp/Program.cs` line 38 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6jlIgEDB980etRY2SU:-N6jlIgEDB980etRY2SV:bakphu) ([raw file](https://github.com/sillsdev/l10nsharp/blob/29d92a24a5dd092c5840ef04276a95017efe03f7/src/SampleApp/Program.cs#L38)):*
> ```Smalltalk
> 		{
> 			if (useTmx)
> 				throw new NotSupportedException("TMX-based localization is no longer supported.");
> ```

What is the advantage of  this over just removing the parameter?
Maybe naïve, but I think I would want a compile-time error rather than a run-time one.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/101)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @ermshiperete, and @jasonleenaylor)

___
*[`src/L10NSharp/LocalizationManagerInternal.cs` line 858 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6jkgzv84jwYr_G0Wr-:-N6msp_R5m3Pz91B5X69:b37kuun) ([raw file](https://github.com/sillsdev/l10nsharp/blob/29d92a24a5dd092c5840ef04276a95017efe03f7/src/L10NSharp/LocalizationManagerInternal.cs#L858)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why does this always want to be "tmx"?
</blockquote></details>

Because I did it wrong

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/101)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 26 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6nIsux84c_Va8x-vk3:-N6nIsux84c_Va8x-vk4:b-8chw5c) ([raw file](https://github.com/sillsdev/l10nsharp/blob/2144b46bf4b44355918af684fe66b6e1903f7cde/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L26)):*
> ```Smalltalk
> 
> 		internal abstract ILocalizationManagerInternal<T> CreateLocalizationManager(string appId,
> 			string appName, string appVersion, string directoryOfInstalledLocFiles,
> ```

Is `L10n` better than `Loc`?



_Code quote:_
```Smalltalk
directoryOfInstalledLocFiles
```

**Comment by tombogle** [comment]
*[`src/L10NSharpTests/LocalizationManagerTestsBase.cs` line 26 at r2](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6nIsux84c_Va8x-vk3:-N6nXCaOBAUWQuukz3IU:bxk3f2u) ([raw file](https://github.com/sillsdev/l10nsharp/blob/2144b46bf4b44355918af684fe66b6e1903f7cde/src/L10NSharpTests/LocalizationManagerTestsBase.cs#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is `L10n` better than `Loc`?
</blockquote></details>

I just looked to see what we (probably me) called it in the actual implementation of the method and used that. FWIW, there are dozens of variables and method names that use Loc and 0 that use L10n, so I don't know if that makes it "better", but at least it is consistent.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete and @jasonleenaylor)

___
*[`src/SampleApp/Program.cs` line 38 at r1](https://reviewable.io/reviews/sillsdev/l10nsharp/101#-N6jlIgEDB980etRY2SU:-N6nj_o0E5HkdXKwOHm4:b-xsbv3p) ([raw file](https://github.com/sillsdev/l10nsharp/blob/29d92a24a5dd092c5840ef04276a95017efe03f7/src/SampleApp/Program.cs#L38)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

This is the sample app. A user (developer) could pass anything on the command line, but it seems reasonably likely that they might have their IDE set to pass -tmx. By throwing this nice exception, I'm hoping to make it clear what the problem is, rather than just ignoring the parameter (as we do with anything else that is unexpected) and making them try to figure out why they are possibly getting some unexpected behavior.
</blockquote></details>

Sorry, I failed to understand the context.

**Pull request merged**
