### PR TITLE
Fix broken Group tests

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/l10nsharp/3)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
So I see how you made the test pass but I'm not sure I understand the impact for users of the library. So when a user decides a string is no longer used they tag it somehow? 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 613 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-KU3pHE1wPAxsVvokbZl:-KU3pHE1wPAxsVvokbZm:b-a4s0ia) ([raw file](https://github.com/sillsdev/l10nsharp/blob/d152e0e2f80d1dd554dfa05c3d603dffdd468b51/src/L10NSharp/LocalizedStringCache.cs#L613)):*
> ```Smalltalk
> 					{
> 						newNode = new LocTreeNode(OwningManager, groupChain[i], null, nodeKey);
> 						nodeCollection.Add(newNode);
> ```

Was this intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-:-KU3oSRrCKaZlMQfQ0bO:b-dawg4h)*

**Comment by jasonleenaylor** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3)*

**Comment by jasonleenaylor** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3)*

**Comment by gmartin7** [comment]
Yes, they mark it with a nolongerused property. And anyway, this code is in the part that handles the x-group property which I've never seen used before.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-:-KU3wzMapW28I1t4Q7_h:b-eld2e6)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 613 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-KU3pHE1wPAxsVvokbZl:-KU3xLfKLIjXe8OceKsR:b-dilo8g) ([raw file](https://github.com/sillsdev/l10nsharp/blob/d152e0e2f80d1dd554dfa05c3d603dffdd468b51/src/L10NSharp/LocalizedStringCache.cs#L613)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary>
> Was this intended?
</details>
Yes, I couldn't see any possible reason to add something to a collection that was being overwritten on the next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3)*

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/L10NSharp/LocalizedStringCache.cs, line 613 at r1](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-KU3pHE1wPAxsVvokbZl:-KUIIZROYregxX5YwKdM:b-s77y3x) ([raw file](https://github.com/sillsdev/l10nsharp/blob/d152e0e2f80d1dd554dfa05c3d603dffdd468b51/src/L10NSharp/LocalizedStringCache.cs#L613)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary>
> Yes, I couldn't see any possible reason to add something to a collection that was being overwritten on the next line.
</details>
I suppose, but I'm curious about how it works with newNode. I see you didn't break anything so I don't really have any objections. :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-:-KUIIropE1Waa4qnnRkF:bnfp4nl)*

**Comment by gmartin7** [comment]
I'll admit to a similar curiosity! :worried: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/l10nsharp/3#-:-KUIJJZxnMneulfQOrYe:b-y0d851)*

**Pull request merged**
